language: node_js
node_js: 0.12
before_install:
  - "npm install -g coffee-script"
  - "npm install path@0.11"
  - "npm install util"
  - "cake build"
script: "make test"
notifications:
  email: false
